# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_laboratorio', models.CharField(max_length=100)),
                ('sigla_laboratorio', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_marcacao', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('data', models.DateField()),
                ('cod_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcacaoLaboratorio.Laboratorio')),
                ('cod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
