# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcacaoLaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='cod_laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Laboratorio'),
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
    ]
