"""
Django settings for LAB project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g+u+witamfyzxs&v&9xi59=7@8n-f!fzypq#r8xko5ud_84cg^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user', # APP DE USUARIO
    'marcacaoLaboratorio', # APP PARA MARCAR LABORATORIO
    'laboratorio', # APP PARA CRIAR UM NOVO LABORATORIO
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LAB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LAB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


# É NECESARIO CRIAR NO MYSQL UM BANCO DE DADOS COM O MESMO NOME
# EXEMPLO : create database lab_uniceub; (lab_uniceub **nome schema**)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # TIPO DE BANCO DE DADOS
        'NAME': 'lab_uniceub', # NOME DO SCHEMA BANCO DE DADOS
        'USER': 'root', # NOME USUARIO DO BANCO DE DADOS
        'PASSWORD': 'aragaoRuan10!', # SENHA BANCO DE DADOS
        'HOST': '127.0.0.1', # HOST BANCO DE DADOS
        'PORT': '3306' # POSTA DO BANCO DE DADOS
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# PARA USAR OS ARQUIVOS DENTRO DA PASTA  static
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# LOGIN URL
LOGIN_URL = '/'